name: Send Custom Metrics to Datadog

on:
  push:
    branches:
      - dev

jobs:
  custom-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send custom metrics to Datadog
        run: |
          curl -X POST "https://api.datadoghq.eu/api/v1/series" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
          -d '{
                "series": [{
                  "metric": "ci.pipeline.duration",
                  "points": [[$(date +%s), 123]],
                  "type": "gauge",
                  "tags": ["ci-provider:github", "env:production", "pipeline:build"]
                }]
              }'
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
