name: Datadog Log Upload via Curl

on:
  push:
    branches:
      - dev

jobs:
  send-logs-to-datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Curl Command to Send Logs to Datadog
        run: |
          echo "Sending logs to Datadog via curl"
           curl -X POST "https://api.datadoghq.eu/api/v1/integration/github" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY": ${{ secrets.DD_API_KEY }} \
          -H "DD-APPLICATION-KEY": ${{ secrets.DD_APP_KEY }} \
          -d '{
             "account_name": ${{ github.repository_owner }},
             "client_id": ${{ secrets.CLIENT_ID_GITHUB_APP }},
             "client_secret": ${{ secrets.SECRET_GITHUB_APP }}
          }'
