name: Datadog CI Metrics Pipeline Integration

on:
  push:
    branches:
      - dev

jobs:
  build-and-upload-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Datadog CI Visibility
        uses: DataDog/ci-visibility-github-action@v0.1.0
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
        env:
          DD_SITE: datadoghq.eu

      - name: Build and Test
        run: |
          echo "Running build steps..."
          # Replace these with your actual build and test commands
          echo "Build completed successfully"

      - name: Upload CI Pipeline Metrics to Datadog
        run: |
          echo "Sending pipeline metrics to Datadog"
