name: Datadog

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  send-metrics-to-datadog:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Datadog Python library
        run: |
          python -m pip install --upgrade pip
          pip install datadog

      - name: Send custom metric to Datadog
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: |
          python -c "
          from datadog import initialize, api
          options = {'api_key': '${DATADOG_API_KEY}'}
          initialize(**options)
          api.Metric.send(metric='github.actions.workflow.run', points=1, tags=['env:production', 'repo:${{ github.repository }}'])
          "
