name: DD CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  monitor-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Datadog CLI
        run: npm install -g @datadog/datadog-ci     

      - name: Upload Pipeline Metrics to Datadog
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        run: |
          # Send custom pipeline metrics to Datadog for CI monitoring
          datadog-ci metrics pipeline upload \
            --pipeline-name "GitHub Actions" \
            --pipeline-id ${{ github.run_id }} \
            --status success
